// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUrGemju9E2MhMdrhuvTrT-ziPU_qkzMs',
    appId: '1:301840818214:web:9a617215652f89d31d46e7',
    messagingSenderId: '301840818214',
    projectId: 'vapelurrr-6d698',
    authDomain: 'vapelurrr-6d698.firebaseapp.com',
    storageBucket: 'vapelurrr-6d698.firebasestorage.app',
    measurementId: 'G-5YP4R6PGLP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbC024-QvP2bXnBl7iAVLvg1Btiyo3tj8',
    appId: '1:301840818214:ios:c84dde54eac778b41d46e7',
    messagingSenderId: '301840818214',
    projectId: 'vapelurrr-6d698',
    storageBucket: 'vapelurrr-6d698.firebasestorage.app',
    iosBundleId: 'com.example.kelompokmodul3Mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbC024-QvP2bXnBl7iAVLvg1Btiyo3tj8',
    appId: '1:301840818214:ios:c84dde54eac778b41d46e7',
    messagingSenderId: '301840818214',
    projectId: 'vapelurrr-6d698',
    storageBucket: 'vapelurrr-6d698.firebasestorage.app',
    iosBundleId: 'com.example.kelompokmodul3Mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUrGemju9E2MhMdrhuvTrT-ziPU_qkzMs',
    appId: '1:301840818214:web:4fc0d1f0aecbba701d46e7',
    messagingSenderId: '301840818214',
    projectId: 'vapelurrr-6d698',
    authDomain: 'vapelurrr-6d698.firebaseapp.com',
    storageBucket: 'vapelurrr-6d698.firebasestorage.app',
    measurementId: 'G-SZ9DW6TVS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNyWDHBqGGvYrUIlBuBpGfKgIB_hA9KJU',
    appId: '1:301840818214:android:5ade01334a0ea3811d46e7',
    messagingSenderId: '301840818214',
    projectId: 'vapelurrr-6d698',
    storageBucket: 'vapelurrr-6d698.firebasestorage.app',
  );

}